{{- if .Values.worker.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
  {{- if and .Values.worker.hpa.customMetricsEnabled .Values.worker.hpa.customMetrics }}
  {{- range .Values.worker.hpa.customMetrics }}
  - type: Pods
    pods:
      metric:
        name: {{ .name }}
        {{- if .filterLabels }}
        selector:
          matchLabels:
            {{- range $k, $v := .filterLabels }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
        {{- end }}
      target:
        type: AverageValue
        averageValue: {{ .targetAverageValue | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.worker.hpa.targetCPUEnabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.worker.hpa.targetMemoryEnabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.hpa.targetMemoryUtilizationPercentage }}
  {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.worker.hpa.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: {{ (index .Values.worker.hpa.behavior.scaleUp.policies 0).type }}
        value: {{ (index .Values.worker.hpa.behavior.scaleUp.policies 0).value }}
        periodSeconds: {{ (index .Values.worker.hpa.behavior.scaleUp.policies 0).periodSeconds }}
      - type: {{ (index .Values.worker.hpa.behavior.scaleUp.policies 1).type }}
        value: {{ (index .Values.worker.hpa.behavior.scaleUp.policies 1).value }}
        periodSeconds: {{ (index .Values.worker.hpa.behavior.scaleUp.policies 1).periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.worker.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: {{ (index .Values.worker.hpa.behavior.scaleDown.policies 0).type }}
        value: {{ (index .Values.worker.hpa.behavior.scaleDown.policies 0).value }}
        periodSeconds: {{ (index .Values.worker.hpa.behavior.scaleDown.policies 0).periodSeconds }}
      - type: {{ (index .Values.worker.hpa.behavior.scaleDown.policies 1).type }}
        value: {{ (index .Values.worker.hpa.behavior.scaleDown.policies 1).value }}
        periodSeconds: {{ (index .Values.worker.hpa.behavior.scaleDown.policies 1).periodSeconds }}
{{- end }}
