{{- if .Values.worker.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
  {{- if .Values.worker.hpa.customMetric.enabled }}
  - type: Pods
    pods:
      metric:
        name: {{ .Values.worker.hpa.customMetric.name }}
      target:
        type: AverageValue
        averageValue: {{ .Values.worker.hpa.customMetric.targetAverageValue | quote }}
  {{- end }}
  {{- if .Values.worker.hpa.targetCPUEnabled }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.hpa.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.worker.hpa.targetMemoryEnabled }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.worker.hpa.targetMemoryUtilizationPercentage }}
  {{- end }}
  behavior: {{ toYaml .Values.worker.hpa.behavior | nindent 4 }}
{{- end }}