apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq-exporter
spec:
  selector:
    app: rabbitmq-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9419
      targetPort: 9419

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
    spec:
      containers:
        - name: rabbitmq-exporter
          image: kbudde/rabbitmq-exporter:latest
          ports:
            - containerPort: 9419
          env:
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-password
            - name: RABBIT_URL
              value: "http://{{ .Values.global.rabbitmqHost }}:15672"