piVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-exporter
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: rabbitmq-exporter
  namespaceSelector:
    matchNames:
      - sentryk8s-dev
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scheme: http
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter-svc
  namespace: sentryk8s-dev
  labels:
    app: rabbitmq-exporter
    app.kubernetes.io/name: rabbitmq-exporter
spec:
  selector:
    app: rabbitmq-exporter
  ports:
    - name: metrics
      port: 9419
      targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter-deployment
  namespace: sentryk8s-dev  
  labels:
    app: rabbitmq-exporter
    app.kubernetes.io/name: rabbitmq-exporter
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
        app.kubernetes.io/name: rabbitmq-exporter
        app.kubernetes.io/component: exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9419"
    spec:
      containers:
        - name: rabbitmq-exporter
          image: kbudde/rabbitmq-exporter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9419
          env:
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-username
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: rabbitmq-password
            - name: RABBIT_URL
              value: "http://sentryk8s-dev-rabbitmq.sentryk8s-dev.svc.cluster.local:15672"
            - name: RABBIT_CAPABILITIES
              value: "no_sort,bert"
            - name: PUBLISH_PORT
              value: "9419"
            - name: OUTPUT_FORMAT
              value: "JSON"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"