apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  clusterIP: None
  selector:
    app: scheduler
  ports:
    - protocol: TCP
      port: {{ .Values.scheduler.service.port }}
      targetPort: {{ .Values.scheduler.service.port }}
