apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics 
    path: /metrics
    interval: 30s
    basicAuth:
      username:
        name: rabbitmq-secrets
        key: rabbitmq-username
      password:
        name: rabbitmq-secrets
        key: rabbitmq-password