apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - protocol: TCP
      port: {{ .Values.worker.service.port }}
      targetPort: {{ .Values.worker.service.port }}
  type: ClusterIP
