apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scheduler
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: "{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}"
        imagePullPolicy: {{ .Values.scheduler.image.pullPolicy }}
        env:
        - name: POSTGRES_HOST
          value: sentryk8s-postgresql
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: sentry_db
        - name: RABBITMQ_HOST
          value: sentryk8s-rabbitmq
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: rabbitmq-password