apiVersion: v2
name: sentryk8s
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: rabbitmq
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 12.1.0
    repository: https://charts.bitnami.com/bitnami