# sentryk8s
scheduler:
  image:
    repository: brennokm/scheduler
    tag: latest
    imagePullPolicy: Always
  replicaCount: 2
  service:
    port: 8000

worker:
  image:
    repository: brennokm/worker
    tag: latest
    imagePullPolicy: Always
  replicaCount: 3
  service:
    port: 8001

rabbitmq:
  auth:
    username: admin
    existingSecret: rabbitmq-secrets
    existingUsernameKey: rabbitmq-username
    existingPasswordKey: rabbitmq-password
    existingErlangCookieKey: rabbitmq-erlang-cookie
  extraEnvVars:
  - name: RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: rabbitmq-secrets
        key: rabbitmq-username
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rabbitmq-secrets
        key: rabbitmq-password
  configuration: |-
    default_user = admin
    default_pass = ${RABBITMQ_PASSWORD}
    loopback_users.admin = false
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*
  persistence:
    enabled: true
    size: 10Gi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 120
    command:
      - sh
      - -ec
      - 'curl -f --user admin:${RABBITMQ_PASSWORD} 127.0.0.1:15672/api/health/checks/virtual-hosts'
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    command:
      - sh
      - -ec
      - 'curl -f --user admin:${RABBITMQ_PASSWORD} 127.0.0.1:15672/api/health/checks/local-alarms'

postgresql:
  auth:
    existingSecret: postgres-secrets
    secretKeys:
      postgres-password-key: password
      username-key: username
  primary:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi