# sentryk8s
global:
  postgresHost: sentryk8s-postgresql
  rabbitmqHost: sentryk8s-rabbitmq

scheduler:
  image:
    repository: brennokm/scheduler
    tag: main-latest
    pullPolicy: Always
  replicaCount: 2
  service:
    port: 8000

worker:
  image:
    repository: brennokm/worker
    tag: main-latest
    pullPolicy: Always
  replicaCount: 3
  service:
    port: 8001

rabbitmq:
  auth:
    username: admin
    existingSecret: rabbitmq-secrets
    existingUsernameKey: rabbitmq-username
    existingPasswordKey: rabbitmq-password
    existingErlangCookieKey: rabbitmq-erlang-cookie
  extraEnvVars:
  - name: RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: rabbitmq-secrets
        key: rabbitmq-username
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rabbitmq-secrets
        key: rabbitmq-password
  configuration: |-
    default_user = admin
    default_pass = ${RABBITMQ_PASSWORD}
    loopback_users.admin = false
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*
  persistence:
    enabled: true
    size: 10Gi
  livenessProbe:
    enabled: false # temporariamente desativado
    initialDelaySeconds: 120
    command:
      - sh
      - -ec
      - 'curl -f --user admin:${RABBITMQ_PASSWORD} 127.0.0.1:15672/api/health/checks/virtual-hosts'
  readinessProbe:
    enabled: false # temporariamente desativado
    initialDelaySeconds: 30
    command:
      - sh
      - -ec
      - 'curl -f --user admin:${RABBITMQ_PASSWORD} 127.0.0.1:15672/api/health/checks/local-alarms'

postgresql:
  auth:
    enablePostgresUser: false
    existingSecret: postgres-secrets
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      usernameKey: username
    username: "admin"
    password: ""  # Desabilita a senha padrão
    database: "sentry_db"
  primary:
    initdb:
      scriptsConfigMap: sentryk8s-initdb
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi