apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 4.7.0
    chart: prometheus-adapter
    helm:
      values: |
        prometheus:
          url: http://prometheus-stack-prometheus.monitoring.svc
          port: 9090
        rules:
          custom:
          - seriesQuery: 'rabbitmq_queue_messages_ready{queue="tasks"}'
            resources:
              overrides:
                namespace: {resource: "namespace"}
            name:
              matches: "rabbitmq_queue_messages_ready"
              as: "rabbitmq_tasks_queue_messages"
            metricsQuery: 'sum(rabbitmq_queue_messages_ready{queue="tasks", namespace!=""}) by (namespace)'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true