name: Build e Push Docker

on:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '.github/workflows/ci.yaml'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Verificar estrutura de pastas (debug)
      run: ls -R

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Verificar estrutura do scheduler
      run: ls -la src/scheduler/

    - name: Build e Push do Scheduler
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./src/scheduler/Dockerfile
        push: true
        tags: |
          brennokm/scheduler:${{ github.ref_name }}-latest
          brennokm/scheduler:${{ github.sha }}
      
    - name: Verificar estrutura do worker
      run: ls -la src/worker/

    - name: Build e Push do Worker
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./src/worker/Dockerfile
        push: true
        tags: |
          brennokm/worker:${{ github.ref_name }}-latest
          brennokm/worker:${{ github.sha }}
